#!/bin/bash
docker run -it --gpus all --ipc=host -p 8888:8888 --mount src=`pwd`/examples,target=/workspace,type=bind --mount src=`pwd`/data,target=/workspace/data,type=bind  --ulimit memlock=-1 --ulimit stack=67108864 -w /workspace nvcr.io/nvidia/merlin/merlin-pytorch:22.06 jupyter notebook --allow-root --no-browser --NotebookApp.token='' --ip=0.0.0.0
